In [2]:
import numpy as np

## 1

In [3]:
arr = np.array([[[1,2],[3,4],[2,3],[5,5]],
                [[3,2],[2,2],[10,1],[2,6]],
                 [[6,7],[8,3],[9,1],[1,2]]])
np.shape(arr)

(3, 4, 2)

In [6]:
print(f'Обращение к элементу {arr[2][3][1]}')
print(f'Еще одно обращение к элементу {arr[2, 3, 1]}')

Обращение к элементу 2
Еще одно обращение к элементу 2


In [9]:
print(f'Каждый второй элемент 2-ой строки:\n {arr[2][::2]}')

Каждый второй элемент 2-ой строки:
 [[6 7]
 [9 1]]


In [12]:
print(f'Из первых двух строк первые два элемента:\n {arr[:2,:2]}')

Из первых двух строк первые два элемента:
 [[[1 2]
  [3 4]]

 [[3 2]
  [2 2]]]


In [14]:
print (f'Первый столбец:\n {arr[:,0]}')

Первый столбец:
 [[1 2]
 [3 2]
 [6 7]]


## 2

In [13]:
N = 10**7
np_1 = np.random.rand(N)
np_2 = np.random.rand(N)



In [14]:
%%timeit
np_res = (np_1 + np_2) / np_1

56.2 ms ± 2.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
list_1 = list(np_1)
list_2 = list(np_2)

In [16]:
%%timeit
list_res = [(x+y)/x for x,y in zip(list_1, list_2)]

2.5 s ± 85.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Очевидно numpy быстрее.

## 3

In [32]:
def linspace(start, stop, num=50):
    return [start + (stop - start)*x / (num-1) for x in range(num)]

In [50]:
%%timeit
np.linspace(start=2, stop=3, num=1000)

26.8 µs ± 966 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [49]:
%%timeit
linspace(start=2, stop=3, num=1000)

281 µs ± 5.83 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Библиотечный побыстрее будет, как и ожидалось.